"""add relation

Revision ID: 2035b5cd7fd3
Revises: 6eb313f97c47
Create Date: 2026-06-14 01:26:00.714458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2035b5cd7fd3'
down_revision: Union[str, Sequence[str], None] = '6eb313f97c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE FUNCTION insert_company_users()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO company(userId)
        VALUES (NEW.id);
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER insert_company_users_trg
    AFTER INSERT ON "user"
    FOR EACH ROW
    EXECUTE FUNCTION insert_company_users();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
    DROP TRIGGER IF EXISTS insert_company_users_trg ON "user";
    """)

    op.execute("""
    DROP FUNCTION IF EXISTS insert_company_users();
    """)
    # ### end Alembic commands ###
