"""add relation

Revision ID: a0b7f2a716f2
Revises: b505d23c3fa4
Create Date: 2026-06-14 01:00:52.542170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b7f2a716f2'
down_revision: Union[str, Sequence[str], None] = 'b505d23c3fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'user', ['userId'], ['id'], ondelete='cascade')
    op.drop_column('company', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'userId')
    # ### end Alembic commands ###
