"""test

Revision ID: a77441acc7f0
Revises: 0cc89988aa13
Create Date: 2026-06-13 19:06:51.865144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77441acc7f0'
down_revision: Union[str, Sequence[str], None] = '0cc89988aa13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('workerId', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'user', ['workerId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'workerId')
    # ### end Alembic commands ###
